import NavbarComponent from "@/components/NavbarComponent";
import SidebarComponent from "@/components/SidebarComponent";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="font-SFProDisplay flex gap-5 mr-14
      "
      >
        <SidebarComponent />
        <div className="w-full">
          <NavbarComponent />
        {children}

        </div>

      </body>
    </html>
  );
}
